import { expect, test } from "@playwright/test";

/**
 * Branding & auth-guard checks — Developed by Laugh Company
 * These specs verify that no "generation tool" branding leaks into the UI
 * and that private routes correctly bounce unauthenticated visitors to /auth.
 */

const PRIVATE_ROUTES = [
  "/dashboard",
  "/pedidos",
  "/clientes",
  "/fornecedores",
  "/financeiro",
  "/relatorios",
  "/configuracoes",
];

const FORBIDDEN_UI = [/lovable/i, /generated by/i, /auto-?generated/i, /powered by ai/i];

test.describe("Login page", () => {
  test("shows 'Developed by Laugh Company' authorship", async ({ page }) => {
    await page.goto("/auth");
    await expect(page.getByText(/Developed by Laugh Company/i)).toBeVisible();
  });

  test("does not surface any forbidden branding string", async ({ page }) => {
    await page.goto("/auth");
    const body = (await page.locator("body").innerText()).toLowerCase();
    for (const rx of FORBIDDEN_UI) {
      expect(body, `body contains forbidden pattern ${rx}`).not.toMatch(rx);
    }
  });
});

test.describe("Private route redirects", () => {
  for (const route of PRIVATE_ROUTES) {
    test(`unauthenticated ${route} redirects to /auth without leaking branding`, async ({ page }) => {
      await page.goto(route);
      await page.waitForURL(/\/auth(\?.*)?$/, { timeout: 10_000 });
      expect(page.url()).toMatch(/\/auth/);

      const body = (await page.locator("body").innerText()).toLowerCase();
      for (const rx of FORBIDDEN_UI) {
        expect(body, `redirect page contains forbidden pattern ${rx}`).not.toMatch(rx);
      }
    });
  }
});
