import { expect, test, type Page } from "@playwright/test";

/**
 * Extended private-route redirect check — every _authenticated route must
 * bounce anonymous visitors to /auth and must never expose the internal
 * "Verificando sessão…" banner along the way.
 */

const PRIVATE_ROUTES = [
  "/dashboard",
  "/pedidos",
  "/clientes",
  "/fornecedores",
  "/financeiro",
  "/relatorios",
  "/configuracoes",
];

const INTERNAL_BANNERS = [
  /Verificando sessão/i,
  /lovable/i,
  /generated by/i,
];

async function bodyText(page: Page) {
  return (await page.locator("body").innerText()).trim();
}

for (const route of PRIVATE_ROUTES) {
  test(`private ${route} redirects to /auth without internal banners`, async ({ page }) => {
    const seen: string[] = [];
    // Sample the DOM every ~120ms while the redirect resolves.
    const interval = setInterval(async () => {
      try {
        seen.push(await bodyText(page));
      } catch {
        /* page might be transitioning */
      }
    }, 120);

    await page.goto(route);
    await page.waitForURL(/\/auth(\?.*)?$/, { timeout: 10_000 });
    clearInterval(interval);
    seen.push(await bodyText(page));

    // Final URL is /auth
    expect(page.url()).toMatch(/\/auth/);

    // None of the DOM snapshots along the way contained forbidden text.
    const combined = seen.join("\n");
    for (const rx of INTERNAL_BANNERS) {
      expect(combined, `${route} leaked pattern ${rx}`).not.toMatch(rx);
    }
  });
}
