-- Reproducible record of security hardening applied to Laugh One.
REVOKE ALL ON FUNCTION public.adjust_product_stock(uuid,numeric,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.adjust_product_stock(uuid,numeric,text,text) TO authenticated;
REVOKE ALL ON FUNCTION public.apply_order_stock_out(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.apply_order_stock_out(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.revert_order_stock(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.revert_order_stock(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.current_user_has_active_subscription() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.current_user_has_active_subscription() TO authenticated;
REVOKE ALL ON FUNCTION public.expire_due_subscriptions() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_module_access_indicators(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_module_access_indicators(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.get_user_company_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_company_id() TO authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_active_subscription(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_active_subscription(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid,public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
REVOKE ALL ON FUNCTION public.is_staff_or_admin(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_staff_or_admin(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.log_audit_event(text,uuid,text,text,jsonb,jsonb,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_audit_event(text,uuid,text,text,jsonb,jsonb,text) TO authenticated;
REVOKE ALL ON FUNCTION public.log_company_activity(text,uuid,text,text,text,text,text,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_company_activity(text,uuid,text,text,text,text,text,uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.log_system_error(uuid,text,text,text,uuid,jsonb,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_system_error(uuid,text,text,text,uuid,jsonb,text) TO authenticated;
REVOKE ALL ON FUNCTION public.bootstrap_current_user_workspace() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.bootstrap_current_user_workspace() TO authenticated;
CREATE OR REPLACE FUNCTION public.tg_set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.check_subscription_status() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN IF NEW.status = 'active' AND NEW.expires_at <= now() THEN NEW.status := 'expired'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.check_profiles_recursion() RETURNS boolean LANGUAGE sql STABLE SET search_path = public AS $$ SELECT false; $$;
